USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(100) DEFAULT 'UNKNOWN',
    name VARCHAR(100) DEFAULT 'UNKNOWN',
    release_date YEAR,
    sales FLOAT DEFAULT '0',
    genre VARCHAR(20) DEFAULT 'UNKNOWN',
    PRIMARY KEY (id)
);